# Generated by Django 4.1.2 on 2022-10-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post_likes_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-profile-pic.png', null=True, upload_to=''),
        ),
    ]
