# Generated by Django 4.1.2 on 2022-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_post_likes_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-post.png', null=True, upload_to=''),
        ),
    ]
